1st PR dev to master
jcwalker/AuditSystemDsc pull request #1
Opened 2019-06-14 16:05 UTC by jcwalker

Initial PR version 1.0, dev to master

2019-06-16 20:35 UTC, japatton approved these changes
Was not able to find any issues. Ran both examples on test box. Both worked. Created a new local user account without password and DSC resource worked as expected reporting it as Not in desired state.

2019-06-16 20:38 UTC, japatton approved these changes

2019-06-17 16:05 UTC, bcwilhite requested changes

2019-06-17 16:05 UTC, bcwilhite commented on DSCResources/AuditSetting/AuditSetting.psm1
> +function Write-PropertyValue
I would consider updating Write-PropertyValue to reduce the verbose output that this resource generates when a Test fails.  With queries that produce myriad CIM/WMI instances, the output is very cluttered, such as Win32_Service.  Furthermore, with CIM/WMI there's a Key property that will uniquely identify each instance that you could use to limit the verbose output.  You can query the "Key" via the Get-CimClass cmdlet.

Example of updated Write-PropertyValue function code:
````PowerShell
function Write-PropertyValue
{
    [OutputType([System.String])]
    [CmdletBinding()]
    param
    (
        [Parameter()]
        [object[]]
        $Object
    )

    $cimFullPathFromQuery = $Object | Select-Object -Property CimClass -Unique
    $cimNameSpace = ($cimFullPathFromQuery.CimClass -split ':')[0]
    $cimClassName = ($cimFullPathFromQuery.CimClass -split ':')[1]
    $cimClassInfo = Get-CimClass -Namespace $cimNameSpace -ClassName $cimClassName -Verbose:$false
    $propertyNames = $cimClassInfo.CimClassProperties.Where({$PSItem.Qualifiers.Name -match 'Key' -and $PSItem.Name -notmatch "CreationClassName"})

    foreach ($propertyName in $propertyNames.Name)
    {
        if ([string]::IsNullOrWhiteSpace($instance.$propertyName) -eq $false)
        {
            "$propertyName`: $(([string]$instance.$propertyName).Trim())"
        }
    }

}
````

2019-06-17 16:05 UTC, bcwilhite commented on DSCResources/AuditSetting/AuditSetting.psm1
> +                foreach ($propertyItem in $(Write-PropertyValue $instance))
Write-PropertyValue is missing the -Object parameter

2019-06-17 16:24 UTC, nehrua commented on DSCResources/AuditSetting/AuditSetting.psm1
> +        The object that contains the pproperties and values to be displayed.
spelling... "pproperties"

2019-06-17 16:24 UTC, nehrua commented on DSCResources/AuditSetting/AuditSetting.psm1
> +
extra line

2019-06-17 16:24 UTC, nehrua commented on DSCResources/AuditSetting/AuditSetting.psm1
> +        $queryResult = Get-CimInstance -Query $Query -ErrorAction Stop
Do you need the -ErrorAction param?  Won't the try/catch handle this?

2019-06-17 16:58 UTC, bcwilhite commented on DSCResources/AuditSetting/AuditSetting.psm1
> +        $queryResult = Get-CimInstance -Query $Query -ErrorAction Stop
So an incorrect query is not a terminating error, so ErrorAction Stop in this case should be correct.

2019-06-17 17:02 UTC, jcwalker commented on DSCResources/AuditSetting/AuditSetting.psm1
> +        $queryResult = Get-CimInstance -Query $Query -ErrorAction Stop
It's needed because of the try/catch.  For try/catch to work it needs to be a terminating error.  The ErrorAction Stop forces it to a terminating error.

2019-06-17 17:02 UTC, jcwalker commented on DSCResources/AuditSetting/AuditSetting.psm1
> +        The object that contains the pproperties and values to be displayed.
not catch.

done.

2019-06-17 17:03 UTC, jcwalker commented on DSCResources/AuditSetting/AuditSetting.psm1
> +                foreach ($propertyItem in $(Write-PropertyValue $instance))
good catch

2019-06-17 17:16 UTC, jcwalker commented on DSCResources/AuditSetting/AuditSetting.psm1
> +
done

2019-06-17 19:41 UTC, jcwalker commented on DSCResources/AuditSetting/AuditSetting.psm1
> +function Write-PropertyValue
I implemented something like this but better.

2019-06-18 02:54 UTC, bcwilhite approved these changes

2019-06-18 10:56 UTC, jcwalker commented on DSCResources/AuditSetting/AuditSetting.psm1
> +        $queryResult = Get-CimInstance -Query $Query -ErrorAction Stop
reply

2019-06-18 17:53 UTC, merged